chat_option(CHAT_ENABLE_WARNING_AS_ERROR "Convert compiler warnings into errors" off)
chat_option(CHAT_ENABLE_ASAN "Enable address sanitizer" off)
chat_option(CHAT_ENABLE_TSAN "Enable thread sanitizer" off)
chat_option(CHAT_ENABLE_UBSAN "Enable undefined sanitizer" off)
chat_option(CHAT_ENABLE_LSAN "Enable leak sanitizer" off)
